version: '3.8'

services:
  backend:
    container_name: chess_backend
    build: ./backend
    restart: always
    networks:
      - web-gateway

  nginx:
    container_name: chess_frontend
    image: nginx:alpine
    restart: always
    # Removed ports 80:80 since the master gateway handles it
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - web-gateway

networks:
  web-gateway:
    name: web-gateway
    external: true
